MODEL:
  TYPE: anynet
  NUM_CLASSES: 5
ANYNET:
  STEM_TYPE: res_stem_in
  STEM_W: 64
  BLOCK_TYPE: res_bottleneck_block
  STRIDES: [1, 2, 2, 2]
  DEPTHS: [3, 4, 6, 3]
  WIDTHS: [256, 512, 1024, 2048]
  BOT_MULS: [0.25, 0.25, 0.25, 0.25]
  GROUP_WS: [64, 128, 256, 512]
OPTIM:
  LR_POLICY: cos
  BASE_LR: 0.2
  MAX_EPOCH: 10
  MOMENTUM: 0.9
  WEIGHT_DECAY: 5e-5
TRAIN:
  DATASET: ./data/cifar10/train.txt
  IM_SIZE: 224
  BATCH_SIZE: 4
TEST:
  DATASET: ./data/cifar10/test.txt
  IM_SIZE: 256
  BATCH_SIZE: 1
GPU_DEVICE_IDS: [0,]
OUT_DIR: .
