MODEL:
  TYPE: resnet
  DEPTH: 50
  NUM_CLASSES: 10
RESNET:
  TRANS_FUN: bottleneck_transform
  WIDTH_PER_GROUP: 64
  STRIDE_1X1: False
BN:
  ZERO_INIT_FINAL_GAMMA: True
OPTIM:
  BASE_LR: 0.0125
  LR_POLICY: steps
  STEPS: [0, 30, 60, 90]
  LR_MULT: 0.1
  MAX_EPOCH: 10
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.0001
TRAIN:
  DATASET: ./data/cifar10/train.txt
  # ./data/cifar10/train.txt
  # ./data/flower_photos/train
  SPLIT: train
  BATCH_SIZE: 2
  IM_SIZE: 224
TEST:
  DATASET: ./data/cifar10/test.txt
  #./data/cifar10/test.txt
  #  ./data/flower_photos/test
  SPLIT: test
  BATCH_SIZE: 1
  IM_SIZE: 256
GPU_DEVICE_IDS: [0,]
DATA_LOADER:
  NUM_WORKERS: 1
CUDNN:
  BENCHMARK: True
OUT_DIR: .
