MODEL:
  TYPE: shufflenetv2
  NUM_CLASSES: 5
  ACTIVATION_FUN: relu
SN:
  STEM_W: 24
  STRIDES: [2,2,2]
  DEPTHS: [4,8,4]
  WIDTHS: [48,96,192]
  HEAD_W: 1024
OPTIM:
  LR_POLICY: cos
  BASE_LR: 0.0125
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-5
TRAIN:
  DATASET: ./data/flower_photos/train.txt
  IM_SIZE: 224
  BATCH_SIZE: 1
TEST:
  DATASET: ./data/flower_photos/test.txt
  IM_SIZE: 256
  BATCH_SIZE: 1
GPU_DEVICE_IDS: [0,]
# GPU_DEVICE_IDS: [0,1,2,3,4,5,6,7]
OUT_DIR: .
