MODEL:
  TYPE: regnet
  NUM_CLASSES: 1000
REGNET:
  DEPTH: 22
  W0: 216
  WA: 55.59
  WM: 2.1
  GROUP_W: 128
OPTIM:
  LR_POLICY: cos
  BASE_LR: 0.4
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  WEIGHT_DECAY: 5e-5
  WARMUP_EPOCHS: 5
TRAIN:
  DATASET: ./data/cifar10/train.txt
  IM_SIZE: 224
  BATCH_SIZE: 512
TEST:
  DATASET: ./data/cifar10/test.txt
  IM_SIZE: 256
  BATCH_SIZE: 400
GPU_DEVICE_IDS: [0,1,2,3,4,5,6,7]
OUT_DIR: .
