MODEL:
  TYPE: regnet
  NUM_CLASSES: 1000
REGNET:
  DEPTH: 23
  W0: 320
  WA: 69.86
  WM: 2.0
  GROUP_W: 168
OPTIM:
  LR_POLICY: cos
  BASE_LR: 0.2
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  WEIGHT_DECAY: 5e-5
  WARMUP_EPOCHS: 5
TRAIN:
  DATASET: ./data/cifar10/train.txt
  IM_SIZE: 224
  BATCH_SIZE: 256
TEST:
  DATASET: ./data/cifar10/test.txt
  IM_SIZE: 256
  BATCH_SIZE: 200
GPU_DEVICE_IDS: [0,1,2,3,4,5,6,7]
OUT_DIR: .
