# The baseline config for v2 models.
MODEL:
  TYPE: effnet_v2
  NUM_CLASSES: 10
  ACTIVATION_FUN: silu
EN:
  STEM_W: 32
  STRIDES: [1, 2, 2, 2, 1, 2]
  DEPTHS: [1, 2, 2, 3, 5, 8]
  WIDTHS: [16, 32, 48, 96, 112, 192]
  EXP_RATIOS: [1, 4, 4, 4, 6, 6]
  KERNELS: [3, 3, 3, 3, 3, 3]
  SE_R: [0, 0, 0, 0.25, 0.25, 0.25]
  HEAD_W: 1024
OPTIM:
  LR_POLICY: cos
  BASE_LR: 0.4
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-5
TRAIN:
  DATASET: ./data/cifar10/train.txt
  IM_SIZE: 224
  BATCH_SIZE: 1
TEST:
  DATASET: ./data/cifar10/test.txt
  IM_SIZE: 256
  BATCH_SIZE: 1
GPU_DEVICE_IDS: [0,]
# GPU_DEVICE_IDS: [0,1,2,3,4,5,6,7]
OUT_DIR: .
