MODEL:
  TYPE: mobilenetv3_small
  NUM_CLASSES: 10
  ACTIVATION_FUN: silu
MBS:
  HEAD_W: 1024

OPTIM:
  LR_POLICY: cos
  BASE_LR: 0.4
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-5
TRAIN:
  DATASET: ./data/cifar10/train.txt
  IM_SIZE: 224
  BATCH_SIZE: 1
TEST:
  DATASET: ./data/cifar10/test.txt
  IM_SIZE: 256
  BATCH_SIZE: 1
GPU_DEVICE_IDS: [0,]
# GPU_DEVICE_IDS: [0,1,2,3,4,5,6,7]
OUT_DIR: .
